// Objective-C API for talking to github.com/curyous/adder Go package.
//   gobind -lang=objc github.com/curyous/adder
//
// File is generated by gobind. Do not edit.

#ifndef __Adder_H__
#define __Adder_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Add3 adds 3
 */
FOUNDATION_EXPORT long AdderAdd3(long a);

#endif
