
// Objective-C API for talking to the following Go packages
//
//	github.com/curyous/adder
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Adder_FRAMEWORK_H__
#define __Adder_FRAMEWORK_H__

#include "Adder.objc.h"
#include "Universe.objc.h"

#endif
